name: build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches: 'master'
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=version::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=version::0.0.0
          fi
        shell: bash
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true
      -
        name: Mage build
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: build
      -
        name: Mage chocoPack
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: chocoPack
      -
        name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WindowsSpyBlocker
          path: |
            bin/WindowsSpyBlocker.exe
            bin/windowsspyblocker.${{ steps.prepare.outputs.version }}.nupkg
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            bin/WindowsSpyBlocker.exe
            bin/windowsspyblocker.${{ steps.prepare.outputs.version }}.nupkg
          name: ${{ steps.prepare.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Mage chocoPush
        uses: magefile/mage-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        with:
          version: latest
          args: chocoPush
